name: Addon Validation

on:
  push:
    paths: [ "addons.json", "**/*.json", "**/*.py" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Fetch Core Version
        id: core_version
        run: |
          wget https://raw.githubusercontent.com/faneX-ID/core/main/backend/main.py -O backend_main.py
          VERSION=$(grep 'version="' backend_main.py | head -n 1 | sed -n 's/.*version="\([^"]*\)".*/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run Integration Validation
        uses: faneX-ID/integration-validation@main
        with:
          core_version: ${{ steps.core_version.outputs.version }}
          working_directory: '.'
